- name: Deploy the Kubernetes Cluster Infrastructure
  hosts: all
  tasks:
  - name: Include Variables from vars.yaml
    include_vars:
      file: vars.yaml

  - import_role:
      name: k8s-create
   
  - name: list the ip address
    shell: openstack stack output show -f json -c output_value {{ stack_name }} ip_address
    register: result

  - name: print debug
    debug:
      msg: "here {{ result.stdout }}"

  - name: set_fact
    set_fact:
      stack_output: "{{ (result.stdout|from_json).output_value }}"

  - debug:
      var: stack_output

  - name: Add the master to the inventory
    add_host:
      name: "{{ stack_output.master.name }}"
      groups: master,all,k8s
      ansible_ssh_host: "{{ stack_output.master.address }}"

  - name: Add the nodes to the inventory
    add_host:
      name: "{{ item.name }}"
      groups: nodes,all,k8s
      ansible_ssh_host: "{{ item.address }}"
    with_items: "{{ stack_output.nodes.address }}"
    
- name: configure all the nodes
  hosts: k8s
  gather_facts: yes
  sudo: yes
  tasks:
  - import_role:
      name: k8s-common

- name: configure the master
  hosts: master
  gather_facts: yes
  sudo: yes
  tasks:
  - import_role:
      name: k8s-master

- name: configure the nodes
  hosts: nodes
  gather_facts: yes
  sudo: yes
  tasks:
  - import_role:
      name: k8s-nodes

- name: configure the master post installation
  hosts: master
  gather_facts: yes
  sudo: yes
  tasks:
  - import_role:
      name: k8s-final
