- name: Deploy the Kubernetes Cluster Infrastructure
  hosts: all
  environment:
    OS_PROJECT_DOMAIN_NAME: 
    OS_USER_DOMAIN_NAME: 
    OS_PROJECT_NAME: 
    OS_USERNAME: 
    OS_PASSWORD: 
    OS_AUTH_URL: 
    OS_IDENTITY_API_VERSION: 
    OS_IMAGE_API_VERSION: 
  tasks:
  - name: Include Variables from vars.yaml
    include_vars:
      file: vars.yaml

  - import_role:
      name: k8s-stack-create

  - name: list the ip address
    shell: openstack stack output show -f value -c output_value {{ stack_name }} ip_address
    register: result

  - name: print debug
    debug:
      msg: "here {{ result.stdout }}"

  - set_fact:
       stack_output: "{{ (result.stdout|from_json).output_value }}"

  - debug:
      var: stack_output
      
  - name: Add the master to the inventory
    add_host:
      name: "{{ stack_output.master.name }}"
      groups: master,all,k8s
      ansible_ssh_host: "{{ stack_output.master.address }}"

  - name: Add the nodes to the inventory
    add_host:
      name: "{{ item.name }}"
      groups: nodes,all,k8s
      ansible_ssh_host: "{{ item.address }}"
    with_items: "{{ stack_output.nodes.address }}"

- name: configure all
  hosts: k8s
  tasks:
  - import_role:
      name: k8s-common

- name: configure master
  hosts: master
  remote_user: cloud-user
  tasks:
  - import_role:
      name: k8s-master

- name: configure nodes
  hosts: nodes
  tasks:
  - import_role:
      name: k8s-nodes
