heat_template_version: 2018-03-02
description:
   An instance for a Kubernetes cluster made up of a masters and nodes
   The instances are created with Heat and then configured with Ansible

parameters:
  node_count:
    type: number
    description: Number of node servers to create.
    default: 1

  node_hostname_prefix:
    type: string
    description: The default prefix for nodes server hostnames
    default: "node"

  node_flavor:
    type: string
    description: The name of the OpenStack instance flavor to use for node servers

  hostname_prefix:
    description: The default prefix for slave server hostnames
    type: string
    default: "node"

  image:
    description: The Glance image to use as a base
    type: string
    default: rhel-server-7.6-x86_64-kvm

  service_network:
    type: string
    description: project network to attach instance to

  external_network:
    type: string
    description: network used for floating IPs

resources:
  nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: node_count}
      resource_def:
        type: k8s-node.yaml
        properties:
          external_network: {get_param: external_network}
          service_network: {get_param: service_network}
          node_flavor: {get_param: node_flavor}
          image: {get_param: image}
          hostname:
            str_replace:
              template: "%prefix%%index%"
              params:
                '%prefix%': {get_param: hostname_prefix}

outputs:
  entries:
    value: {get_attr: [nodes, entry]}
