heat_template_version: 2018-03-02
description: Template to spawn an cirros instance.

parameters:
  node_count:
    type: number
    description: Number of node servers to create.
    default: 1

  node_hostname_prefix:
    type: string
    description: The default prefix for nodes server hostnames
    default: "node"

  node_flavor:
    type: string
    description: The name of the OpenStack instance flavor to use for node servers

  hostname_prefix:
    description: The default prefix for slave server hostnames
    type: string
    default: "node"

  image:
    description: The Glance image to use as a base
    type: string
    default: rhel-server-7.6-x86_64-kvm

  key_name:
    type: string
    description: keypair to be used
    default: paas-keypair

  service_network:
    type: string
    description: project network to attach instance to

  external_network:
    type: string
    description: network used for floating IPs

  hostname:
    type: string
    description: hostname for the nodes

resources:
  server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: "HOSTNAME"
          params:
            HOSTNAME: {get_param: hostname}
      config_drive: true
      block_device_mapping:
        - device_name: vda
          delete_on_termination: true
          volume_id: { get_resource: volume }
      flavor: {get_param: node_flavor}
      key_name: {get_param: key_name}
      networks:
        - port: { get_resource: port }

  port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: service_network}
      security_groups:
        - default

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: external_network}
      port_id: { get_resource: port }

  volume:
    type: OS::Cinder::Volume
    properties:
      image: {get_param: image}
      size: 100

outputs:
  entry:
    description: Floating IP address of server in public network
    value:
      name: {get_param: hostname}
      address: {get_attr: [floating_ip, floating_ip_address ]}
