heat_template_version: 2018-03-02
description:
   An instance for a Kubernetes cluster made up of a masters and nodes
   The instances are created with Heat and then configured with Ansible

parameters:
  node_count:
    type: number
    description: Number of node servers to create.
    default: 1

  node_hostname_prefix:
    type: string
    description: The default prefix for nodes server hostnames
    default: "node"

  node_flavor:
    type: string
    description: The name of the OpenStack instance flavor to use for node servers

  image:
    description: The Glance image to use as a base
    type: string
    default: rhel-server-7.6-x86_64-kvm

  master_flavor:
    description: The name of the OpenStack instance flavor to use for master servers
    type: string

  master_hostname:
    description: The default prefix for master server hostnames
    type: string
    default: "master"

  service_network:
    type: string
    description: project network to attach instance to

  external_network:
    type: string
    description: network used for floating IPs

resources:
  hosts:
    type: k8s-hosts.yaml
    properties:
      external_network: {get_param: external_network}
      service_network: {get_param: service_network}
      master_hostname: {get_param: master_hostname}
      master_flavor: {get_param: master_flavor}
      image: {get_param: image}
      node_flavor: {get_param: node_flavor}
      node_hostname_prefix: {get_param: node_hostname_prefix}
      node_count: {get_param: node_count}

outputs:
  ip_address:
    description: The floating IP address of the kubernetes servers
    value:
      master:
        name: { get_param: master_hostname }
        address: {get_attr: [hosts, master_ip_address]}
      nodes:
        address: {get_attr: [hosts, nodes_ip_address]}
